version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cupcakes
      POSTGRES_PASSWORD: cupcakes
      POSTGRES_DB: cupcakes
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
